//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
namespace AssemblyCSharp
{
	public class CommandeTransformation : Commande
	{
		private GameObject objetBase;
		private GameObject objetTransforme;
		private GameObject scorer;

		public CommandeTransformation (GameObject pObjetBase, GameObject pObjetTransforme, GameObject pScorer)
		{
			objetBase = pObjetBase;
			objetTransforme = pObjetTransforme;
			scorer = pScorer;
		}

		public void Executer()
		{
			objetBase.SetActive (false);
			objetTransforme.SetActive (true);
			scorer.SendMessage ("OnScorePlus");
		}

		public void Annuler()
		{
			objetBase.SetActive (true);
			objetTransforme.SetActive (false);
			scorer.SendMessage ("OnScoreMoins");
		}
	}
}

